namespace ObliqueStrategies;

internal static class ObliqueStrategiesDeck
{
    public static string[] Cards =
     {
        "Make it more sensual",
        "Do the words need changing?",
        "Remember those quiet evenings",
        "Spectrum analysis",
        "Take away the important parts",
        "Honour thy error as a hidden intention",
        "Repetition is a form of change",
        "Emphasise repetitions",
        "Disconnect from desire",
        "Voice your suspicions",
        "Is the intonation correct?",
        "Imagine the music as a moving chain or caterpillar",
        "Make an exhaustive list of everything you might do and do the last thing on the list",
        "It is quite possible (after all)",
        "Mechanicalise something idiosyncratic",
        "Take a break",
        "Cascades",
        "Do nothing for as long as possible",
        "The inconsistency principle",
        "Simple subtraction",
        "Trust in the you of now",
        "\"Decorate, decorate\"",
        "Retrace your steps",
        "You can only make one dot at a time",
        "Do the last thing first",
        "Towards the insignificant",
        "Consider different fading systems",
        "Cut a vital connection",
        "Accretion",
        "Always first steps",
        "The tape is now the music",
        "Turn it upside down",
        "Abandon normal instruments",
        "Don't be frightened to display your talents",
        "It is simply a matter of work",
        "Who should be doing this job? How would they do it?",
        "How would you have done it?",
        "Overtly resist change",
        "Be extravagant",
        "Mute and continue",
        "Short circuit (example; a man eating peas with the idea that they will improve his virility shovels them straight into his lap)",
        "Left channel, right channel, centre channel",
        "What would your closest friend do?",
        "Which elements can be grouped?",
        "Is the tuning intonation correct?",
        "Go to an extreme, come part way back",
        "Destroy",
        "Not building a wall but making a brick",
        "What to increase? What to reduce? What to maintain?",
        "Consider transitions",
        "Don't break the silence",
        "You don't have to be ashamed of using your own ideas",
        "Only a part, not the whole",
        "Think of the radio",
        "Ask your body",
        "Breathe more deeply",
        "Once the search has begun, something will be found",
        "What wouldn't you do?",
        "Put in earplugs",
        "Idiot glee(?)",
        "Into the impossible",
        "Voice nagging suspicions",
        "Is something missing?",
        "(Organic) machinery",
        "Remove a restriction",
        "Is there something missing?",
        "Discard an axiom",
        "Is the style right?",
        "Imagine the piece as a set of disconnected events",
        "Would anyone want it?",
        "Use 'unqualified' people",
        "Make what's perfect more human",
        "Give the game away",
        "Remove specifics and convert to ambiguities",
        "Change instrument roles",
        "Emphasise the flaws",
        "What to maintain?",
        "The most important thing is the thing most easily forgotten",
        "From nothing to more than nothing",
        "Don't be frightened of clichés",
        "Be dirty",
        "Accept advice",
        "Do the washing up",
        "Use an unacceptable colour",
        "Consult other sources",
        "A line has two sides",
        "Think",
        "Disciplined self-indulgence",
        "Children's voices",
        "Distorting time",
        "Your mistake was a hidden intention",
        "Is the tuning appropriate?",
        "Use clichés",
        "Fill every beat with something",
        "Slow preparation, fast execution",
        "Tidy up",
        "Which parts can be grouped?",
        "Go slowly all the way round the outside",
        "Display your talent",
        "Look closely at the most embarrassing details and amplify them",
        "What are the sections sections of? Imagine a caterpillar moving",
        "You are an engineer",
        "What are you really thinking about just now? Incorporate",
        "Discover your formulas and abandon them",
        "Move towards the unimportant",
        "Be less critical",
        "What mistakes did you make last time?",
        "Distort time",
        "The most easily forgotten thing is the most important",
        "State the problem as clearly as possible",
        "Make a blank valuable by putting it in an exquisite frame",
        "Openly resist change",
        "Feedback recordings into an acoustic situation",
        "Work at a different speed",
        "Change specifics to ambiguities",
        "Look at the order in which you do things",
        "Gardening, not architecture",
        "Emphasise differences",
        "What is the simplest solution?",
        "Where's the edge? Where does the frame start?",
        "Twist the spine",
        "Convert a melodic element into a rhythmic element",
        "Balance the consistency principle with the inconsistency principle",
        "Intentions",
        "Assemble some of the elements in a group and treat the group",
        "Simply a matter of work",
        "Always the first steps",
        "When is it for?",
        "Which frame would make this look right?",
        "Always give yourself credit for having more than personality(given by Arto Lindsay)",
        "Faced with a choice, do both (given by Dieter Rot)",
        "Make something implied more definite (reinforce, duplicate)",
        "Ghost echoes",
        "What context would look right?",
        "Use an old idea",
        "Is it finished?",
        "Use something nearby as a model",
        "Ask people to work against their better judgement"
    };
}